---

language: python
python: "2.7"
install:
  - sudo apt-get update -qq
  - pip install ansible
  - echo -e 'localhost  ansible_connection=local' > inventory
script:
  - ansible-playbook -i inventory --syntax-check tests/playbook.yml
  - ansible-playbook -i inventory tests/playbook.yml
