---

- name: restart redis
  service:
    name: redis-server
    state: "restarted"
  become: yes
  become_method: sudo

- name: restart sentinel
  service:
    name: redis-sentinel
    state: "restarted"
  become: yes
  become_method: sudo
